adding libpropeller back as a module and adding ability to install to any path

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,3 +1,66 @@
 #! /bin/bash
 
-cd deps/libpropeller && ./configure.static 
+# Defaults
+
+PREFIX="/usr/local"
+
+# Help
+
+show_help() {
+cat <<EOF
+Configure leda.
+
+--help                      This help.
+--prefix=DIR                Prefix where Leda should be installed.
+                            Default is $PREFIX
+
+EOF
+}
+
+# Parse options
+
+while [ -n "$1" ]
+do
+   value="`echo $1 | sed 's/[^=]*.\(.*\)/\1/'`"
+   key="`echo $1 | sed 's/=.*//'`"
+   if `echo "$value" | grep "~" >/dev/null 2>/dev/null`
+   then
+      echo
+      echo '*WARNING*: the "~" sign is not expanded in flags.'
+      echo 'If you mean the home directory, use $HOME instead.'
+      echo
+   fi
+   case "$key" in
+   --help)
+      show_help
+      exit 0
+      ;;
+   --prefix)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      PREFIX="$value"
+      ;;
+   *)
+      die "Error: Unknown flag: $1"
+      ;;
+   esac
+   shift
+done
+
+cat <<EOF > config.mk
+# This file was automatically generated by the configure script.
+# Run "./configure --help" for details.
+DEST=$PREFIX
+EOF
+
+cp config.mk deps/luajit
+
+# update git modules if needed
+if [ -e ".gitmodules" ]
+then
+    git submodule init
+    git submodule update
+fi
+
+# configure libpropeller
+cd deps/libpropeller && ./configure --static 
+
